# Generated by Django 3.2.14 on 2022-12-18 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20221218_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='followed_by', to='profiles.UserProfile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='unfollows',
            field=models.ManyToManyField(blank=True, related_name='unfollowed_by', to='profiles.UserProfile'),
        ),
    ]
